package common;

public enum Chapter {
    ALL,
        MAIN_SCRIPT,
            PROLOGUE,
            CHAPTER1,
                CHAPTER1_EL,
                CHAPTER1_NL,
                CHAPTER1_TRIAL,
            CHAPTER2,
                CHAPTER2_EL,
                CHAPTER2_NL,
                CHAPTER2_TRIAL,
            CHAPTER3,
                CHAPTER3_EL,
                CHAPTER3_NL,
                CHAPTER3_TRIAL,
            CHAPTER4,
                CHAPTER4_EL,
                CHAPTER4_NL,
                CHAPTER4_TRIAL,
            CHAPTER5,
                CHAPTER5_EL,
                CHAPTER5_NL,
                CHAPTER5_TRIAL,
            CHAPTER6,
                CHAPTER6_EL,
                CHAPTER6_NL,
                CHAPTER6_TRIAL,
            EPILOGUE,
        FTE,
        UNKNOWN//TODO check
}
